title: Laboratoire citoyen
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
site:
  lang: fr-CA
  author: Ricky Ng-Adam
lang: fr-CA

languages: ["fr", "en"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: fr
languageNames:
  fr: Français
  en: English
